Repository ssu-capstone2-DeunDeun/DeunDeun-frontend, pull requests merged in 2021-06, with the labels that each got.

#53 Feature/#51
  deundeun/src/app.jsx
  deundeun/src/components/ClubWritePost/index.jsx
  deundeun/src/components/ClubWritePost/styles.js
  deundeun/src/components/common/AnswerCard/index.jsx
  deundeun/src/components/common/Button/styles.js
  deundeun/src/components/common/QuestionCard/index.jsx
  deundeun/src/components/common/SideBar/index.jsx
  deundeun/src/container/application/ApplicationAddContainer.js
  deundeun/src/container/recruit/RecruitAddInfoContainer.js
  deundeun/src/modules/applicationAddInfo.js
  deundeun/src/modules/clubAddRecruitInfo.js
  deundeun/src/modules/index.js
  deundeun/src/modules/recruitAddInfo.js
  deundeun/src/modules/writePost.js
  deundeun/src/pages/ApplicationAddPage/index.jsx
  deundeun/src/pages/ClubPostPage/index.jsx
  deundeun/src/pages/ClubPostPage/styles.js
  deundeun/src/pages/RecruitAddPage/index.jsx
  deundeun/src/pages/RecruitAddPage/styles.js
Labels: Development

#69 Fix/#67
  deundeun/src/components/ApplicationFormCard/index.jsx
  deundeun/src/components/ApplicationFormCard/styles.js
  deundeun/src/components/modal/DeleteApplicationModal/index.jsx
  deundeun/src/components/modal/DeleteApplicationModal/styles.js
  deundeun/src/pages/ApplicationManagePage/index.jsx
  deundeun/src/pages/ApplicationManagePage/styles.js
Labels: feature, fix, frontend

#76 fix: 지원서 작성 시 단일 선택 구현
  deundeun/src/app.jsx
  deundeun/src/components/apply/CheckList/index.jsx
  deundeun/src/pages/ApplicationAddPage/index.jsx
  deundeun/src/pages/ApplicationSuccessPage/index.jsx
  deundeun/src/pages/ApplicationSuccessPage/styles.js
  deundeun/src/pages/ApplySuccessPage/index.jsx
  deundeun/src/pages/ApplySuccessPage/styles.js
  deundeun/src/pages/RecruitAddPage/index.jsx
  deundeun/src/pages/RecruitSuccessPage/index.jsx
  deundeun/src/pages/RecruitSuccessPage/styles.js
Labels: fix, frontend
